version: '3.1'

services:

  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      #MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:

# docker-compose up -d
# docker-compose down --rmi all
# docker-compose down -v
# docker exec -i -t db mysql -uuser -ppassword